In [73]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [40]:
df = pd.read_csv("dataset/place.csv")

In [41]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB


In [43]:
df.describe()

cgpa     package
count  200.000000  200.000000
mean     6.990500    2.996050
std      1.069409    0.691644
min      4.260000    1.370000
25%      6.190000    2.487500
50%      6.965000    2.995000
75%      7.737500    3.492500
max      9.580000    4.620000

In [44]:
df.isnull().sum()

cgpa       0
package    0
dtype: int64

In [45]:
x = pd.DataFrame(df.iloc[:,0])

In [46]:
x

cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [47]:
y = pd.DataFrame(df.iloc[:,1])

In [48]:
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [50]:
x_train

cgpa
113  6.94
63   9.16
39   7.43
90   7.11
162  5.53
..    ...
178  8.15
171  8.01
94   5.83
124  6.06
10   5.32

[160 rows x 1 columns]

In [51]:
x_test

cgpa
158  5.95
92   7.90
120  5.23
115  8.35
48   8.63
30   7.36
65   7.60
196  5.89
25   7.28
169  9.31
58   6.92
6    6.73
100  7.95
99   6.61
4    6.94
67   6.51
183  7.28
181  8.22
154  7.08
187  6.26
85   4.79
191  7.28
75   6.97
199  6.22
111  5.42
73   8.44
7    6.75
172  6.93
42   5.95
87   8.09
9    8.31
80   7.63
192  8.25
175  7.04
182  5.88
170  6.22
114  5.84
79   7.18
193  4.57
57   6.60

In [52]:
y_train

package
113     2.37
63      4.25
39      3.33
90      2.66
162     2.55
..       ...
178     3.63
171     3.76
94      2.42
124     2.31
10      1.86

[160 rows x 1 columns]

In [53]:
y_test

package
158     3.04
92      4.00
120     1.73
115     4.21
48      4.09
30      3.26
65      3.81
196     2.57
25      3.65
169     4.37
58      3.09
6       2.60
100     4.14
99      3.24
4       3.57
67      2.89
183     2.72
181     3.89
154     2.85
187     2.44
85      1.48
191     3.48
75      3.28
199     2.33
111     2.25
73      4.03
7       2.48
172     2.51
42      2.54
87      3.55
9       3.51
80      3.44
192     3.75
175     3.50
182     2.08
170     2.87
114     1.87
79      3.00
193     1.94
57      1.94

In [54]:
lr = LinearRegression()

In [55]:
lr.fit(x_train,y_train)

LinearRegression()

In [56]:
y_pred = lr.predict(x_test)
y_pred

array([[2.40113496],
       [3.48271892],
       [2.00178088],
       [3.73231521],
       [3.88761958],
       [3.18320336],
       [3.31632138],
       [2.36785545],
       [3.13883068],
       [4.26478732],
       [2.93915364],
       [2.83376854],
       [3.51045184],
       [2.76720953],
       [2.95024681],
       [2.71174368],
       [3.13883068],
       [3.66020962],
       [3.027899  ],
       [2.57307907],
       [1.75773117],
       [3.13883068],
       [2.96688657],
       [2.55089274],
       [2.10716599],
       [3.78223447],
       [2.84486171],
       [2.94470023],
       [2.40113496],
       [3.58810402],
       [3.71012888],
       [3.33296114],
       [3.67684937],
       [3.00571266],
       [2.36230887],
       [2.55089274],
       [2.34012253],
       [3.08336484],
       [1.63570631],
       [2.76166294]])

In [57]:
r2_LR = r2_score(y_test,y_pred)
r2_LR

0.7713861048540888

In [74]:
mse_LR = mean_squared_error(y_test,y_pred)
mse_LR

0.1303916354123156

In [75]:
mae_LR = mean_absolute_error(y_test,y_pred)
mae_LR

0.3104264809323574

In [94]:
rmse_LR=np.sqrt(mse_LR)

**RandomForestRegressor**

In [58]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=100,random_state=0)
rfr.fit(x_train,y_train)

C:\Users\CS-L2-PC15\AppData\Local\Temp\ipykernel_8124\592262364.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfr.fit(x_train,y_train)


RandomForestRegressor(random_state=0)

In [59]:
y_pred1 = rfr.predict(x_test)
y_pred1

array([2.4314    , 3.53010333, 1.80015   , 3.8898    , 4.1567    ,
       3.0047    , 3.0974    , 2.49885786, 3.150515  , 3.8671    ,
       2.81623667, 3.247     , 3.77025   , 2.5549    , 2.78346417,
       2.885175  , 3.150515  , 3.8713    , 3.307625  , 3.021375  ,
       1.5573    , 3.150515  , 3.03454833, 2.294755  , 2.0879    ,
       3.6625    , 2.80495   , 2.81623667, 2.4314    , 3.898     ,
       3.5164    , 3.7302    , 3.7062    , 3.0879    , 2.49885786,
       2.294755  , 2.65497048, 2.6845    , 1.5453    , 2.4039    ])

In [69]:
r2_RFR = r2_score(y_test,y_pred1)
r2_RFR

0.703974211505244

In [77]:
mse_RFR = mean_squared_error(y_test,y_pred)
mse_RFR

0.1303916354123156

In [80]:
mae_RFR = mean_absolute_error(y_test,y_pred)
mae_RFR

0.3104264809323574

In [93]:
rmse_RFR=np.sqrt(mse_RFR)

**SupportVectorRegression**

In [61]:
from sklearn.svm import SVR
svr = SVR(kernel='rbf')
svr.fit(x_train,y_train)

C:\Users\CS-L2-PC15\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [62]:
y_pred2 = svr.predict(x_test)
y_pred2

array([2.42311118, 3.54618824, 1.90528933, 3.85205754, 3.96280907,
       3.17325958, 3.32527916, 2.38758359, 3.1281962 , 3.94078878,
       2.94415156, 2.84800071, 3.58413916, 2.7852996 , 2.95411195,
       2.73198797, 3.1281962 , 3.77584296, 3.02389544, 2.59644473,
       1.60662   , 3.1281962 , 2.96903146, 2.57457287, 2.05956026,
       3.89608358, 2.85829456, 2.94913369, 2.42311118, 3.68761404,
       3.83010239, 3.34612575, 3.79463373, 3.00386914, 2.38155793,
       2.57457287, 2.35712052, 3.07489607, 1.55184367, 2.78000669])

In [63]:
r2_SVR = r2_score(y_test,y_pred2)
r2_SVR

0.7770340925759478

In [82]:
mse_SVR = mean_squared_error(y_test,y_pred)
mse_SVR

0.1303916354123156

In [83]:
mae_SVR = mean_absolute_error(y_test,y_pred)
mae_SVR

0.3104264809323574

In [91]:
rmse_SVR=np.sqrt(mse_SVR)

**LassoRegression**

In [64]:
from sklearn.linear_model import Lasso
la = Lasso(alpha = 3.0)
la.fit(x_train,y_train)

Lasso(alpha=3.0)

In [65]:
y_pred3 = la.predict(x_test)
y_pred3

array([2.982625, 2.982625, 2.982625, 2.982625, 2.982625, 2.982625,
       2.982625, 2.982625, 2.982625, 2.982625, 2.982625, 2.982625,
       2.982625, 2.982625, 2.982625, 2.982625, 2.982625, 2.982625,
       2.982625, 2.982625, 2.982625, 2.982625, 2.982625, 2.982625,
       2.982625, 2.982625, 2.982625, 2.982625, 2.982625, 2.982625,
       2.982625, 2.982625, 2.982625, 2.982625, 2.982625, 2.982625,
       2.982625, 2.982625, 2.982625, 2.982625])

In [66]:
r2_LA = r2_score(y_test,y_pred3)
r2_LA

-0.007899898079263723

In [85]:
mse_LA = mean_squared_error(y_test,y_pred)
mse_LA

0.1303916354123156

In [86]:
mae_LA = mean_absolute_error(y_test,y_pred)
mae_LA

0.3104264809323574

In [90]:
rmse_LA=np.sqrt(mse_LA)

In [95]:
df1 = pd.DataFrame({'Regression_Name':['LinearRegression','RandomForestRegression','SupportVectorRegression','LassoRegression'],'r2_score':[r2_LR,r2_RFR,r2_SVR,r2_LA],'mse':[mse_LR,mse_RFR,mse_SVR,mse_LA],'mae':[mae_LR,mae_RFR,mae_SVR,mae_LA],'rmse':[rmse_LR,rmse_RFR,rmse_SVR,rmse_LA]})
df1


Regression_Name  r2_score       mse       mae      rmse
0         LinearRegression  0.771386  0.130392  0.310426  0.361098
1   RandomForestRegression  0.703974  0.130392  0.310426  0.361098
2  SupportVectorRegression  0.777034  0.130392  0.310426  0.361098
3          LassoRegression -0.007900  0.130392  0.310426  0.361098