In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("dataset/Housing.csv")
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [7]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [8]:
df.shape

(545, 13)

In [9]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [10]:
X = pd.DataFrame(df)

In [11]:
X.drop(columns=['price'],inplace=True)

In [12]:
X

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    7420         4          2        3      yes        no       no   
1    8960         4          4        4      yes        no       no   
2    9960         3          2        2      yes        no      yes   
3    7500         4          2        2      yes        no      yes   
4    7420         4          1        2      yes       yes      yes   
..    ...       ...        ...      ...      ...       ...      ...   
540  3000         2          1        1      yes        no      yes   
541  2400         3          1        1       no        no       no   
542  3620         2          1        1      yes        no       no   
543  2910         3          1        1       no        no       no   
544  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 12 columns]

In [13]:
Y = pd.DataFrame(df['price'])

In [14]:
Y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,train_size=0.8)

In [16]:
X_train

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
189  3540         2          1        1       no       yes      yes   
456  2398         3          1        1      yes        no       no   
81   4000         3          2        2      yes        no      yes   
446  3986         2          2        1       no       yes      yes   
282  2175         3          1        2       no       yes      yes   
..    ...       ...        ...      ...      ...       ...      ...   
263  3968         3          1        2       no        no       no   
143  4800         5          2        3       no        no      yes   
106  5450         4          2        1      yes        no      yes   
487  5400         4          1        2      yes        no       no   
198  5948         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
189              no              no        0       no   semi-furnished  
456              no              no        0      yes   semi-furnished  
81               no             yes        1       no   semi-furnished  
446              no              no        1       no      unfurnished  
282              no             yes        0       no      unfurnished  
..              ...             ...      ...      ...              ...  
263              no              no        0       no   semi-furnished  
143             yes              no        0       no      unfurnished  
106              no             yes        0      yes   semi-furnished  
487              no              no        0       no      unfurnished  
198              no             yes        0       no   semi-furnished  

[436 rows x 12 columns]

In [17]:
X_test

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
447  3500         2          1        1       no        no      yes   
246  3520         3          1        1      yes        no       no   
318  4340         3          1        1      yes        no       no   
330  4050         2          1        2      yes       yes      yes   
288  5040         3          1        2      yes        no      yes   
..    ...       ...        ...      ...      ...       ...      ...   
483  6615         3          1        2      yes        no       no   
458  3850         3          1        2      yes        no       no   
160  6210         4          1        4      yes       yes       no   
98   6600         3          2        3      yes        no       no   
384  4500         2          1        1       no        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
447              no              no        0       no   semi-furnished  
246              no              no        0      yes   semi-furnished  
318              no              no        0       no   semi-furnished  
330              no              no        0      yes      unfurnished  
288              no             yes        0       no      unfurnished  
..              ...             ...      ...      ...              ...  
483              no              no        0       no   semi-furnished  
458              no              no        0       no      unfurnished  
160              no             yes        0       no        furnished  
98               no             yes        0      yes      unfurnished  
384              no              no        0       no        furnished  

[109 rows x 12 columns]

In [18]:
Y_train

price
189  5040000
456  3118850
81   6615000
446  3150000
282  4270000
..       ...
263  4410000
143  5600000
106  6160000
487  2870000
198  4935000

[436 rows x 1 columns]

In [19]:
Y_test

price
447  3150000
246  4550000
318  4060000
330  3990000
288  4200000
..       ...
483  2940000
458  3115000
160  5460000
98   6293000
384  3570000

[109 rows x 1 columns]

In [20]:
tr = ColumnTransformer(transformers=[
    #('t1',SimpleImputer(),['horsepower']),
    ('std',OneHotEncoder(drop='first',sparse=False),['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']),
    ('t2',OrdinalEncoder(categories=[['furnished','semi-furnished','unfurnished']]),['furnishingstatus'])
], remainder='passthrough')

In [21]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('std',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['mainroad', 'guestroom', 'basement',
                                  'hotwaterheating', 'airconditioning',
                                  'prefarea']),
                                ('t2',
                                 OrdinalEncoder(categories=[['furnished',
                                                             'semi-furnished',
                                                             'unfurnished']]),
                                 ['furnishingstatus'])])

In [22]:
a = tr.fit_transform(X_train)

In [23]:
a

array([[0., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 1., ..., 2., 2., 1.],
       ...,
       [1., 0., 1., ..., 2., 1., 0.],
       [1., 0., 0., ..., 1., 2., 0.],
       [1., 0., 0., ..., 1., 2., 0.]])

In [24]:
b = tr.fit_transform(X_test)

In [25]:
b

array([[0., 0., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 1., 0., ..., 1., 4., 0.],
       [1., 0., 0., ..., 2., 3., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
lr = LinearRegression()

In [28]:
lr.fit(a,Y_train)

LinearRegression()

In [29]:
lr.predict(b)

array([[2751847.46475517],
       [3510575.78885602],
       [3056843.45563643],
       [4564151.39147423],
       [4799157.78240848],
       [3300499.10875208],
       [4648404.19033583],
       [7847839.44232098],
       [5637176.51535645],
       [4236399.70043513],
       [2877177.27032713],
       [2150847.22766199],
       [3876428.91679194],
       [4095243.94678815],
       [8490254.76463902],
       [4261599.44637114],
       [5873738.55672268],
       [4140563.88411031],
       [4424753.16955008],
       [3100603.37942902],
       [6143724.77050843],
       [3221943.73162286],
       [6535305.63992837],
       [2646727.19149832],
       [4082688.79501126],
       [3109880.79126874],
       [5322872.85812579],
       [6970234.20704127],
       [6448319.56262591],
       [8210627.97790194],
       [5378483.87219296],
       [2637713.42304712],
       [4749453.67810883],
       [6304664.09430492],
       [5079297.94633382],
       [2576220.04924808],
       [3887246.16202004],
 

In [30]:
lr.score(a,Y_train)

0.6773295753561593

In [31]:
lr.score(b,Y_test)

0.6793811512795436