# NUMPY Library

In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE  A 1-D ARRAY USING ARRAY()

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# CREATE  A 1-D ARRAY USING ARANGE()

In [5]:
import numpy as np
a = np.arange(4)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2 3]
int32
(4,)


# CREATE A 2-D ARRAY USING ARRAY()

In [6]:
import numpy as np
a = np.array(([1,2,3],[4,5,6]))
print(a)
print(a.dtype)
print(a.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# CREATE A 2-D ARRAY USING arange()

In [8]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)
print(a.dtype)
print(a.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


# CREATE A 3-D ARRAY USING ARRAY()

In [9]:
import numpy as np
a = np.array([
    [[1,2,3],[4,5,6,]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
    ]
)
print(a)
print(a.dtype)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int32
(3, 2, 3)


# CREATE A 3-D ARRAY USING arange()

In [10]:
import numpy as np
a = np.arange(18).reshape(3,2,3)
print(a)
print(a.dtype)
print(a.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)


# CREATING ARRAY OF ONES (1-D)

In [11]:
import numpy as np
a = np.ones(2,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[1 1]
int32
(2,)


# CREATING ARRAY OF ONES (2-D)

In [12]:
import numpy as np
a = np.ones((2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# CREATING ARRAY OF ONES (3-D)

In [14]:
import numpy as np
a = np.ones((3,2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# CREATE ARRAY OF ZEROS(1-D)

In [15]:
import numpy as np
a = np.zeros((3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[0 0 0]
int32
(3,)


# CREATE ARRAY OF ZEROS(2-D)

In [16]:
import numpy as np
a = np.zeros((2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


# CREATE ARRAY OF ZEROS(3-D)

In [20]:
import numpy as np
a = np.zeros((3,2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32
(3, 2, 3)


# CREATE AN ARRAY WITN RAMDOM NUMBER (1-D)

In [21]:
import numpy as np
a = np.random.randint(2,6,size=(4))
print(a)
print(a.dtype)
print(a.shape)

[4 2 5 2]
int32
(4,)


# CREATE AN ARRAY WITN RAMDOM NUMBER (2-D)

In [22]:
import numpy as np
a = np.random.randint(2,11,size=(2,3))
print(a)
print(a.dtype)
print(a.shape)

[[2 5 9]
 [3 3 3]]
int32
(2, 3)


# CREATE AN ARRAY WITN RAMDOM NUMBER (3-D)

In [26]:
import numpy as np
a = np.random.randint(10,21,size=(3,2,3))
print(a)
print(a.dtype)
print(a.shape)

[[[11 16 13]
  [18 16 18]]

 [[13 14 20]
  [20 20 10]]

 [[14 19 11]
  [17 15 15]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [27]:
import numpy as np
a = np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 8 13 23]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [28]:
import numpy as np
a = np.random.randint([1,2,3],5)
print(a)
print(a.dtype)
print(a.shape)

[1 3 4]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW MULTIPLE HIGH

In [30]:
import numpy as np
a = np.random.randint([1,2,3],[10,20,30],size=(3,1,3))
print(a)
print(a.dtype)
print(a.shape)

[[[ 7 13 10]]

 [[ 5  9  9]]

 [[ 4  2 21]]]
int32
(3, 1, 3)


# CREATE AN ARRAY USING RANDN ()

In [1]:
import numpy as np
a = np.random.randn(3)
print(a)

[-0.05628036  1.20248126  2.82231253]


In [2]:
import numpy as np
a = np.random.randn(3,3)
print(a)

[[ 0.16575333  0.29553368 -1.18448901]
 [ 0.56419002 -0.34754842  0.4318418 ]
 [ 1.55842063 -0.35734004 -1.77519529]]


# CREATE AN ARRAY USING RAND ()

In [4]:
import numpy as np
a = np.random.rand(3,3)
print(a)

[[0.62714969 0.19667488 0.81286405]
 [0.09325445 0.85366219 0.77941742]
 [0.04613104 0.54100507 0.04349008]]


In [5]:
import numpy as np
a = np.random.rand(3,2,3)
print(a)

[[[0.09064686 0.78265764 0.42781354]
  [0.8914109  0.37710591 0.01920168]]

 [[0.66264594 0.93845241 0.4491098 ]
  [0.65461724 0.9179232  0.51766571]]

 [[0.2877414  0.96765034 0.41215164]
  [0.90249074 0.25297177 0.99681734]]]


# POSITIVE INDEXING IN ARRAY

In [14]:
#array with 1-D
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[4])
print(arr[2])

5
3


In [13]:
#array with 2-D
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,2])
print(arr[1,2])

3
6


In [23]:
#array with 3-D
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr[2,1,0])

16


# NEGETIVE INDEXING IN ARRAY

In [24]:
#arry with 1-D
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[-2])

4


In [25]:
#arry with 2-D
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[-0,-2])

2


In [30]:
#arry with 3-D
import numpy as np
arr = np.array(
[
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
]
)
print(arr[-1,-2,-3])
print(arr[-2,-2,-2])

7
2


# NUMPY ARRAY SLICING

slice elements from index 1 to index 5 from following array:

In [31]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


slice elements from index 4 to the end of the array

In [33]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


slice elements from the beginning to index 4(not included)

In [35]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGETIVE SLICING

slice from the index 3 from the end to index 1 from the end:

In [37]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


return every other elements from index 1 to index 5

In [38]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


return every other element from the entire array

In [39]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# SLICING 2-D ARRAY

from the second elements,slice elements from index 1 to index 4(not included)

In [40]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


from both arrays ,return index 2:

In [41]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


from both arrays,slice index 1 to index 4(not included),this will return 2-D array

In [42]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]


# NUMPY ARRAY COPY VS VIEW

#The copy owns the data and any changes made to the copyed array it will not affect the original array,and any changes made to the original array will not affect the copied array.

#The view does not own the data and changes made to the view will affect the original array and changes made to the original array will affect to the view

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
a = arr.copy
print("original array")
print(arr)
print("affected array")


original array
[1 2 3 4 5]


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
print("original array")
print(arr)
print(x)
print("affected array")


original array
[1 2 3 4 5]
[1 2 3 4 5]


# reshape() FUNCTION

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("original array :",arr) #1-d

#2D ARRAY
b = arr.reshape(5,2)
print("2D array with shape 5x2")
print(b)

c = arr.reshape(2,5)
print("2D array with shape 2x5")
print(c)

#3D ARRAY
d = arr.reshape(2,1,5)
print("3D array with shape")
print(d)

original array : [ 1  2  3  4  5  6  7  8  9 10]
2D array with shape 5x2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2D array with shape 2x5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array with shape
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


In [26]:
import numpy as np
arr = np.array([1,2,3,4,5]) #1D
print("original 1D array :",arr)
print(f"sum = {np.sum(arr)}")
print()
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("original 2D array:",arr1)
print(f"sum = {np.sum(arr1)}")
print()
arr2 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
   ])
print("original 3D array:",arr2)
print(f"sum = {np.sum(arr2)}")
print()

original 1D array : [1 2 3 4 5]
sum = 15

original 2D array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
sum = 55

original 3D array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
sum = 78



# AGREEGATION FUNCTION

# sum() FUNCTION

In [11]:
#np.sum(array_name , axis = 0 or 1)
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)

original array : [[1 2 3 4]
 [5 6 7 8]]


# mean() FUNCTION

In [12]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print("original array :",arr)
print("mean :",arr.mean())

original array : [1 2 3 4 5 6 7 8]
mean : 4.5


In [16]:
# import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)
print("Across Rows") #column wise
print("mean = ",np.mean(arr , axis=0))
print("Across columns") #Row wise
print("mean = ",np.mean(arr , axis=1))

original array : [[1 2 3 4]
 [5 6 7 8]]
Across Rows
mean =  [3. 4. 5. 6.]
Across columns
mean =  [2.5 6.5]


# std() FUNCTION

In [15]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)
print()
print("standard div:",np.std(arr))

original array : [[1 2 3 4]
 [5 6 7 8]]

standard div: 2.29128784747792


In [19]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)

print("Across Rows") #column wise
print("std div = ",np.std(arr , axis=0))
print()
print("Across columns") #Row wise
print("std div = ",np.std(arr , axis=1))
print()

original array : [[1 2 3 4]
 [5 6 7 8]]
Across Rows
std div =  [2. 2. 2. 2.]

Across columns
std div =  [1.11803399 1.11803399]



# var() FUNCTION

In [20]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)
print()
print("varient:",np.var(arr))

original array : [[1 2 3 4]
 [5 6 7 8]]

varient: 5.25


In [21]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)

print("Across Rows") #column wise
print("var = ",np.var(arr , axis=0))
print()
print("Across columns") #Row wise
print("var = ",np.var(arr , axis=1))
print()

original array : [[1 2 3 4]
 [5 6 7 8]]
Across Rows
var =  [4. 4. 4. 4.]

Across columns
var =  [1.25 1.25]



# min( ) FUNCTION

In [22]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)
print()
print("minimun:",np.min(arr))

original array : [[1 2 3 4]
 [5 6 7 8]]

minimun: 1


In [23]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)

print("Across Rows") #column wise
print("min = ",np.min(arr , axis=0))
print()
print("Across columns") #Row wise
print("min = ",np.min(arr , axis=1))
print()

original array : [[1 2 3 4]
 [5 6 7 8]]
Across Rows
min =  [1 2 3 4]

Across columns
min =  [1 5]



# max( ) FUNCTION

In [24]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)
print()
print("maximum:",np.max(arr))

original array : [[1 2 3 4]
 [5 6 7 8]]

maximum: 8


In [25]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)

print("Across Rows") #column wise
print("max = ",np.max(arr , axis=0))
print()
print("Across columns") #Row wise
print("max = ",np.max(arr , axis=1))
print()

original array : [[1 2 3 4]
 [5 6 7 8]]
Across Rows
max =  [5 6 7 8]

Across columns
max =  [4 8]

