# NUMPY Library

In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE  A 1-D ARRAY USING ARRAY()

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# CREATE  A 1-D ARRAY USING ARANGE()

In [5]:
import numpy as np
a = np.arange(4)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2 3]
int32
(4,)


# CREATE A 2-D ARRAY USING ARRAY()

In [6]:
import numpy as np
a = np.array(([1,2,3],[4,5,6]))
print(a)
print(a.dtype)
print(a.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# CREATE A 2-D ARRAY USING arange()

In [8]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)
print(a.dtype)
print(a.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


# CREATE A 3-D ARRAY USING ARRAY()

In [9]:
import numpy as np
a = np.array([
    [[1,2,3],[4,5,6,]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
    ]
)
print(a)
print(a.dtype)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int32
(3, 2, 3)


# CREATE A 3-D ARRAY USING arange()

In [10]:
import numpy as np
a = np.arange(18).reshape(3,2,3)
print(a)
print(a.dtype)
print(a.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)


# CREATING ARRAY OF ONES (1-D)

In [11]:
import numpy as np
a = np.ones(2,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[1 1]
int32
(2,)


In [12]:
import numpy as np
a = np.ones((2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


In [14]:
import numpy as np
a = np.ones((3,2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# CREATE ARRAY OF ZEROS(1-D)

In [15]:
import numpy as np
a = np.zeros((3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[0 0 0]
int32
(3,)


# CREATE ARRAY OF ZEROS(2-D)

In [16]:
import numpy as np
a = np.zeros((2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


# CREATE ARRAY OF ZEROS(3-D)

In [20]:
import numpy as np
a = np.zeros((3,2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32
(3, 2, 3)


# CREATE AN ARRAY WITN RAMDOM NUMBER (1-D)

In [21]:
import numpy as np
a = np.random.randint(2,6,size=(4))
print(a)
print(a.dtype)
print(a.shape)

[4 2 5 2]
int32
(4,)


# CREATE AN ARRAY WITN RAMDOM NUMBER (2-D)

In [22]:
import numpy as np
a = np.random.randint(2,11,size=(2,3))
print(a)
print(a.dtype)
print(a.shape)

[[2 5 9]
 [3 3 3]]
int32
(2, 3)


# CREATE AN ARRAY WITN RAMDOM NUMBER (3-D)

In [26]:
import numpy as np
a = np.random.randint(10,21,size=(3,2,3))
print(a)
print(a.dtype)
print(a.shape)

[[[11 16 13]
  [18 16 18]]

 [[13 14 20]
  [20 20 10]]

 [[14 19 11]
  [17 15 15]]]
int32
(3, 2, 3)
