# PANDAS SERIES

Series is an 1D labeled array capable of holding data of any type(integer,float,python object, etc).The axis labeled are collectivelly called as index

#syntax : pd.series(data,index,dtype,copy)

In [3]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5])
print(ser1)
print()
ser2 = pd.Series(['a','b','c','d'])
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64

0    a
1    b
2    c
3    d
dtype: object


In [4]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],dtype = np.float64)
print(ser1)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [7]:
import numpy as np
import pandas as pd
ser1 = pd.Series([1,2,3,4,5],index=["num1","num2","num3","num4","num5"])
print(ser1)

num1    1
num2    2
num3    3
num4    4
num5    5
dtype: int64


In [8]:
import numpy as np
import pandas as pd
i = pd.Index(["num1","num2","num3","num4","num5"])
ser1 = pd.Series([1,2,3,4,5],i)
print(ser1)

num1    1
num2    2
num3    3
num4    4
num5    5
dtype: int64


In [9]:
import numpy as np
import pandas as pd
ser1 = pd.Series({"Rohit":40,"KL Rahul":30,"Virat":60,"Panth":35,"Hardik":40})
print(ser1)

Rohit       40
KL Rahul    30
Virat       60
Panth       35
Hardik      40
dtype: int64


# DATA FRAMES

DataFrame is the collection of multiple Series

# pd.DataFrame(array_name , index , columns )

In [2]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)      #Numpy Array
df = pd.DataFrame(arr , index=['a','b','c'], columns=['A','B','C'])
print(df)       #Pandas DataFrame

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [3]:
#A single array stores marks of one student in every subject
import numpy as np
import pandas as pd
df = pd.DataFrame([[19,20,18,16],[16,16,14,14],[20,12,13,15]], index=['Abhinav','Harshad','Gururaj'], columns=['OSA','PYTHON','JAVA','SE'])
print(df)

         OSA  PYTHON  JAVA  SE
Abhinav   19      20    18  16
Harshad   16      16    14  14
Gururaj   20      12    13  15


In [4]:
#Here, Dictionary in Dataframe ,Single arrays stores marks of every student in one subject
import numpy as np
import pandas as pd
df = pd.DataFrame({"Osa":[23,20,19,25],"Python":[12,20,32,24],"Java":[17,20,18,15],"SE":[12,10,18,3]}
                 ,index=[1,2,3,4]
                 )
print(df)

   Osa  Python  Java  SE
1   23      12    17  12
2   20      20    20  10
3   19      32    18  18
4   25      24    15   3


In [11]:
import numpy as np
import pandas as pd
#Error : All arrays must be of same length
df = pd.DataFrame({"Osa":[23,20,19,25],"Python":[12,20,32]})
print(df)

ValueError: All arrays must be of the same length

In [12]:
import pandas as pd
ser1=pd.Series([22,10,13]) #Take index in Series
ser2=pd.Series([17,17,18,16])
df = pd.DataFrame({"OSA":ser1,"Python":ser2})#Dont take index in dictionary dataframe
print(df)

    OSA  Python
0  22.0      17
1  10.0      17
2  13.0      18
3   NaN      16


# CREATE DATAFRAME CONTAINING INFORMATION ABOUT CITIES

Possibilities of Creating Dataframe through Multiple series

1.Normal Series

2.Transpose Series

3.Dictionary Series(key == Heading , values == series)(Dont need to give name in series)

4.2-d Array (Here,a single array consists of pop and cap of one state)

In [13]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
#print(i)
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
#print(pop)
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="Capital")
#print(cap)
#pin = pd.Series(["586 101","392 479","123 456"],index = i , name = "Pin Code")
#df = pd.DataFrame([pop,cap])
#df = pd.DataFrame([pop,cap,pin]).T
df = pd.DataFrame([["7.1","Bangalore"],["12.4","Mumbai"],["8.9","Gandinagar"]],index=i,columns=["Population","Capital"])
#df =pd.DataFrame({"Population":pop,"Capital":cap,"PinCode":pin})
print(df)

            Population     Capital
Karnataka          7.1   Bangalore
Maharashtra       12.4      Mumbai
Gujarat            8.9  Gandinagar


# How to Add new data to a series

In [60]:
import numpy as np
import pandas as pd
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
pop.append(pd.Series({"TamilNadu":9.8}))
#print(pop)

C:\Users\CS-L2-PC15\AppData\Local\Temp\ipykernel_10768\2976333882.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"TamilNadu":9.8}))


Karanataka     7.1
Maharastra    12.4
Gujurat        8.9
TamilNadu      9.8
dtype: object

In [61]:
import numpy as np
import pandas as pd
df = pd.DataFrame([["7.1","Bangalore"],["12.4","Mumbai"],["8.9","Gandinagar"]],index=i,columns=["Population","Capital"])#DataFrame created in one line
#print(df)
print(df.append(pd.DataFrame([["5.5","Chennai"],["14.2","Hyderabad"]],index=["Tamil Nadu","Andhra Pradesh"],columns=["Population","Capital"])))

               Population     Capital
Karanataka            7.1   Bangalore
Maharastra           12.4      Mumbai
Gujurat               8.9  Gandinagar
Tamil Nadu            5.5     Chennai
Andhra Pradesh       14.2   Hyderabad


C:\Users\CS-L2-PC15\AppData\Local\Temp\ipykernel_10768\3235531569.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([["5.5","Chennai"],["14.2","Hyderabad"]],index=["Tamil Nadu","Andhra Pradesh"],columns=["Population","Capital"])))


In [62]:
import numpy as np
import pandas as pd
i = pd.Index(["Karnataka","Maharashtra","Gujarat"])
pop=pd.Series(['7.1','12.4','8.9'],index=i,name="Population")
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="Capital")
df = pd.DataFrame({"Population":pop,"Capital":cap})
#print(df)
print(df.append(pd.DataFrame({"Population":pd.Series([5.5,14.2],index=["Tamil Nadu","Andhra Pradesh"]),
    "Capital":pd.Series({"Tamil Nadu":"Chennai","Andhra Pradesh":"Hyderabad"})
    })
)
)

               Population      Capital
Karnataka             7.1    Bangalore
Maharashtra          12.4       Mumbai
Gujarat               8.9  Gandhinagar
Tamil Nadu            5.5      Chennai
Andhra Pradesh       14.2    Hyderabad


C:\Users\CS-L2-PC15\AppData\Local\Temp\ipykernel_10768\2891639623.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"Population":pd.Series([5.5,14.2],index=["Tamil Nadu","Andhra Pradesh"]),


# CONCAT NEW COLUMN TO DATAFRAME

In [14]:
import numpy as np
import pandas as pd
i = pd.Index(["Karanataka","Maharastra","Gujurat"])
pop = pd.Series(["4.9","9.0","8.9"],index=i,name="population")
cap = pd.Series(["Bengalure","Mumbai","Gandhinagar"],index=i,name="Capital")
df = pd.DataFrame({"population":pop,"capital":cap})
#print(df)
df1 = pd.concat(
          [df,pd.DataFrame({
                          "Area":pd.Series(["2.1","3.2","5.5"],index=pop.index),
                          "CM":pd.Series(["Bomai","Shinde","xyz"],index=pop.index)
        })
          ],axis=1
)
df1.to_csv("cities_csv")
print(df1)


           population      capital Area      CM
Karanataka        4.9    Bengalure  2.1   Bomai
Maharastra        9.0       Mumbai  3.2  Shinde
Gujurat           8.9  Gandhinagar  5.5     xyz


# PANDAS SUBSETTING

In [19]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
ser1 = Series(np.arange(5), index=["alpha","beta","gama","delta","elipson"])
print(ser1)

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32


In [22]:
ser1[:2]

alpha    0
beta     1
dtype: int32

In [21]:
ser1[["beta","delta"]]

beta     1
delta    3
dtype: int32

In [24]:
ser1["beta":"delta"]

beta     1
gama     2
delta    3
dtype: int32

In [27]:
ser1[ser1>3]

elipson    4
dtype: int32

In [28]:
print(ser1 > 3)

alpha      False
beta       False
gama       False
delta      False
elipson     True
dtype: bool


In [34]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
ser2 = Series(["zero","one","two","three","four"], index=[3,2,4,0,1])
print(ser2)

3     zero
2      one
4      two
0    three
1     four
dtype: object


In [35]:
ser2[2:4]

4      two
0    three
dtype: object

In [36]:
ser2.iloc[2:4] #uses default indexing

4      two
0    three
dtype: object

In [37]:
ser2.iloc[2:4] #uses series indexing

4      two
0    three
dtype: object

In [44]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
df = pd.DataFrame(np.arange(21).reshape(7,3), columns=['AAA','BBB','CCC'], index=["alpha","beta","gama","delta","epsilon","zeta","eta"])
df

AAA  BBB  CCC
alpha      0    1    2
beta       3    4    5
gama       6    7    8
delta      9   10   11
epsilon   12   13   14
zeta      15   16   17
eta       18   19   20

In [46]:
df.AAA

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [47]:
df['AAA']

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [48]:
df[['BBB','CCC']]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [49]:
df.iloc[1:3, 1:2] # SYNTAX : df.iloc[row,colum]

BBB
beta    4
gama    7

In [50]:
df.loc["beta":"delta","BBB":"CCC"]

BBB  CCC
beta     4    5
gama     7    8
delta   10   11

In [51]:
df.iloc[:, 1:3]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [52]:
df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']]

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [56]:
df2=df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']].copy()
df2

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [57]:
df2['CCC'] = Series({'alpha':11, 'gama':18, 'zeta':5})
df2

BBB  CCC
alpha    1   11
gama     7   18
zeta    16    5

In [58]:
df2.iloc[1, 1] = 2
df2

BBB  CCC
alpha    1   11
gama     7    2
zeta    16    5

In [59]:
df2.iloc[:, 1] = 0
df2

BBB  CCC
alpha    1    0
gama     7    0
zeta    16    0