In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("dataset/titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1       0.0       3   
1              2       NaN       1   
2              3       NaN       3   
3              4       NaN       1   
4              5       0.0       3   
..           ...       ...     ...   
886          887       0.0       2   
887          888       1.0       1   
888          889       0.0       3   
889          890       1.0       1   
890          891       0.0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female   NaN      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282      NaN   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [6]:
df.shape

(891, 12)

In [7]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [8]:
df.head()

PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       NaN       1   
2            3       NaN       3   
3            4       NaN       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282      NaN   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [10]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0.0       3    male  22.0      1      0   7.2500        S
1         NaN       1  female  38.0      1      0  71.2833        C
2         NaN       3  female   NaN      0      0      NaN        S
3         NaN       1  female  35.0      1      0  53.1000        S
4         0.0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886       0.0       2    male  27.0      0      0  13.0000        S
887       1.0       1  female  19.0      0      0  30.0000        S
888       0.0       3  female   NaN      1      2  23.4500        S
889       1.0       1    male  26.0      0      0  30.0000        C
890       0.0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [11]:
df.isnull().sum()

Survived      4
Pclass        0
Sex           0
Age         178
SibSp         0
Parch         0
Fare          3
Embarked      2
dtype: int64

In [12]:
df.dropna(subset=['Survived','Fare','Embarked'],inplace=True,axis=0)

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [14]:
X = df.drop(columns=["Survived"])
X

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
4         3    male  35.0      0      0   8.0500        S
5         3    male   NaN      0      0   8.4583        Q
6         1    male  54.0      0      0  51.8625        S
7         3    male   2.0      3      1  21.0750        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[883 rows x 7 columns]

In [15]:
Y = df[["Survived"]]
Y

Survived
0         0.0
4         0.0
5         0.0
6         0.0
7         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[883 rows x 1 columns]

In [16]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,train_size=0.8)

In [17]:
X_train

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
655       2    male  24.0      2      0   73.5000        S
759       1  female  33.0      0      0   86.5000        S
433       3    male  17.0      0      0    7.1250        S
279       3  female  35.0      1      1   20.2500        S
318       1  female  31.0      0      2  164.8667        S
..      ...     ...   ...    ...    ...       ...      ...
124       1    male  54.0      0      1   77.2875        S
199       2  female  24.0      0      0   13.0000        S
836       3    male  21.0      0      0    8.6625        S
738       3    male   NaN      0      0    7.8958        S
861       2    male  21.0      1      0   11.5000        S

[706 rows x 7 columns]

In [18]:
X_test

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
245       1    male  44.0      2      0   90.0000        Q
31        1  female   NaN      1      0  146.5208        C
172       3  female   1.0      1      1   11.1333        S
482       3    male  50.0      0      0    8.0500        S
747       2  female  30.0      0      0   13.0000        S
..      ...     ...   ...    ...    ...       ...      ...
109       3  female   NaN      1      0   24.1500        Q
879       1  female  56.0      0      1   83.1583        C
222       3    male  51.0      0      0    8.0500        S
246       3  female  25.0      0      0    7.7750        S
444       3    male   NaN      0      0    8.1125        S

[177 rows x 7 columns]

In [19]:
Y_train

Survived
655       0.0
759       1.0
433       0.0
279       1.0
318       1.0
..        ...
124       0.0
199       0.0
836       0.0
738       0.0
861       0.0

[706 rows x 1 columns]

In [20]:
Y_test

Survived
245       0.0
31        1.0
172       1.0
482       0.0
747       1.0
..        ...
109       1.0
879       1.0
222       0.0
246       0.0
444       1.0

[177 rows x 1 columns]

In [21]:
tr = ColumnTransformer(transformers=[
    ('t1',SimpleImputer(),['Age']),
    ('t2',OneHotEncoder(drop='first',sparse=False),['Sex','Embarked'])
], remainder='passthrough')

In [22]:
tr.fit_transform(X_train)

array([[24.        ,  1.        ,  0.        , ...,  2.        ,
         0.        , 73.5       ],
       [33.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 86.5       ],
       [17.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  7.125     ],
       ...,
       [21.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  8.6625    ],
       [29.76394366,  1.        ,  0.        , ...,  0.        ,
         0.        ,  7.8958    ],
       [21.        ,  1.        ,  0.        , ...,  1.        ,
         0.        , 11.5       ]])

In [23]:
tr.fit_transform(X_test)

array([[ 44.        ,   1.        ,   1.        , ...,   2.        ,
          0.        ,  90.        ],
       [ 29.20178571,   0.        ,   0.        , ...,   1.        ,
          0.        , 146.5208    ],
       [  1.        ,   0.        ,   0.        , ...,   1.        ,
          1.        ,  11.1333    ],
       ...,
       [ 51.        ,   1.        ,   0.        , ...,   0.        ,
          0.        ,   8.05      ],
       [ 25.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   7.775     ],
       [ 29.20178571,   1.        ,   0.        , ...,   0.        ,
          0.        ,   8.1125    ]])

In [24]:
df_t = tr.fit_transform(df).shape

In [25]:
tr.fit_transform(df)

array([[22.        ,  1.        ,  0.        , ...,  1.        ,
         0.        ,  7.25      ],
       [35.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  8.05      ],
       [29.65278249,  1.        ,  1.        , ...,  0.        ,
         0.        ,  8.4583    ],
       ...,
       [29.65278249,  0.        ,  0.        , ...,  1.        ,
         2.        , 23.45      ],
       [26.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , 30.        ],
       [32.        ,  1.        ,  1.        , ...,  0.        ,
         0.        ,  7.75      ]])